---
- name: Install required package
  apt:
    name: logstash
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Configure Logstash
  template:
    src: logstash.conf.j2
    dest: /etc/logstash/conf.d/logstash.conf
  when: ansible_distribution == "Ubuntu"

- name: Enable Logstash service
  service:
    name: logstash
    state: restarted
    enabled: true
  when: ansible_distribution == "Ubuntu"
